"""Backward-compatible re-exports for Event Arbitration V0.1 configuration."""

from config.arbitration import (
    DECISIVE_EVENT_EVIDENCE_MARGIN,
    MAX_END_FRAME_DIFFERENCE,
    MAX_RELEASE_FRAME_DIFFERENCE,
    MAX_START_FRAME_DIFFERENCE,
    MIN_PASS_TRAJECTORY_QUALITY,
    MIN_SHOT_TRAJECTORY_QUALITY,
    MIN_TEMPORAL_OVERLAP_RATIO,
    RELATIVE_DISTANCE_TOLERANCE,
)
from config.arbitration import EVENT_ARBITRATION_VERSION as VERSION

__all__ = [
    "DECISIVE_EVENT_EVIDENCE_MARGIN",
    "MAX_END_FRAME_DIFFERENCE",
    "MAX_RELEASE_FRAME_DIFFERENCE",
    "MAX_START_FRAME_DIFFERENCE",
    "MIN_PASS_TRAJECTORY_QUALITY",
    "MIN_SHOT_TRAJECTORY_QUALITY",
    "MIN_TEMPORAL_OVERLAP_RATIO",
    "RELATIVE_DISTANCE_TOLERANCE",
    "VERSION",
]
