"""Centralized provisional Event Arbitration V0.1 thresholds."""

MAX_RELEASE_FRAME_DIFFERENCE = 1
MAX_START_FRAME_DIFFERENCE = 2
MAX_END_FRAME_DIFFERENCE = 2
MIN_TEMPORAL_OVERLAP_RATIO = 0.80
RELATIVE_DISTANCE_TOLERANCE = 0.15
DECISIVE_EVENT_EVIDENCE_MARGIN = 0.15
MIN_PASS_TRAJECTORY_QUALITY = 0.40
MIN_SHOT_TRAJECTORY_QUALITY = 0.40
VERSION = "event_arbitration_v0.1"
